# Generated by Django 6.0.4 on 2026-05-05 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conferencerole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conferencerole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='conference',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='conference_logos/'),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='registration_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description_sr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='review_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='submission_mode',
            field=models.CharField(choices=[('full', 'Full paper only'), ('abstract', 'Abstract first, then full paper')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='conferencerole',
            name='role',
            field=models.CharField(choices=[('manager', 'Paper manager'), ('judge', 'Judge'), ('content_reviewer', 'Content reviewer'), ('layout_reviewer', 'Layout reviewer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
