# Generated by Django 6.0.4 on 2026-05-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_submission_final_comment_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('abstract_submitted', 'Abstract submitted'), ('abstract_accepted', 'Abstract accepted'), ('paper_submitted', 'Full paper submitted'), ('decision_made', 'Final decision sent')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
        ),
    ]
