# Generated by Django 6.0.4 on 2026-05-06 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_submission_topic_conferencerole_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencerole',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='conferences.conference'),
        ),
        migrations.AlterField(
            model_name='conferencerole',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('reviewer', 'Reviewer'), ('author', 'Author')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conferencerole',
            unique_together={('user', 'conference', 'role')},
        ),
    ]
