# Generated by Django 6.0.4 on 2026-05-08 13:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0019_review_auto_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='coauthor_emails',
            field=models.TextField(blank=True, help_text='Enter co-author emails, one per line.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='full_paper_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='papers/'),
        ),
    ]
