# Generated by Django 6.0.4 on 2026-05-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0020_submission_coauthor_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='secondary_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_submissions', to='conferences.conferencetopic'),
        ),
    ]
