# Generated by Django 6.0.4 on 2026-05-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0028_email_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['event']},
        ),
    ]
