# Generated by Django 6.0.4 on 2026-05-12 14:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0030_submission_code_and_anonymous_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceinfocard',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='conference_files/'),
        ),
    ]
