# Generated by Django 6.0.4 on 2026-05-05 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_mode',
            field=models.CharField(choices=[('abstract_then_paper', 'Abstract first, then full paper'), ('full_paper_only', 'Full paper only')], default='abstract_then_paper', max_length=30),
        ),
        migrations.AddField(
            model_name='submission',
            name='abstract_file',
            field=models.FileField(blank=True, null=True, upload_to='abstracts/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='full_paper_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.conference'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('abstract_submitted', 'Abstract submitted'), ('abstract_under_review', 'Abstract under review'), ('abstract_accepted', 'Abstract accepted'), ('abstract_rejected', 'Abstract rejected'), ('paper_submitted', 'Full paper submitted'), ('paper_under_review', 'Full paper under review'), ('revision_required', 'Revision required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
