# Generated by Django 6.0.4 on 2026-05-05 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_submissionchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('judge', 'Judge'), ('content_reviewer', 'Content reviewer'), ('layout_reviewer', 'Layout reviewer')], max_length=50)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.submission')),
            ],
            options={
                'unique_together': {('submission', 'reviewer', 'role')},
            },
        ),
    ]
