# Generated by Django 6.0.4 on 2026-05-05 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('revision_required', 'Revision required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('submission', 'reviewer')},
        ),
    ]
