# Generated by Django 6.0.4 on 2026-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='conference_hero/'),
        ),
        migrations.AddField(
            model_name='conference',
            name='template_style',
            field=models.CharField(choices=[('green', 'Green Building'), ('modern', 'Modern'), ('classic', 'Classic')], default='green', max_length=20),
        ),
    ]
