# Generated by Django 6.0.4 on 2026-05-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_conference_hero_image_conference_template_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='conference_files/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='conferences.conference')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
