# Generated by Django 6.0.4 on 2026-05-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_conferenceinfocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='conferences.conference')),
            ],
            options={
                'ordering': ['order', 'code'],
                'unique_together': {('conference', 'code')},
            },
        ),
    ]
