# Generated by Django 6.0.4 on 2026-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_alter_conferencerole_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='coauthors',
            field=models.TextField(blank=True, help_text='Separate co-authors with commas or new lines.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='first_author',
            field=models.CharField(default='Unknown author', max_length=255),
            preserve_default=False,
        ),
    ]
