# Generated by Django 6.0.4 on 2026-05-07 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_alter_conferencerole_role_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.AddField(
            model_name='review',
            name='arguments_discussion',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='comments_for_authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comments_for_editors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='conclusions_supported',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='conflict_of_interest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='content_context',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='contribution',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='engagement_sources',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='english_quality',
            field=models.CharField(choices=[('needs_improvement', 'The English could be improved.'), ('fine', 'The English is fine and does not require improvement.')], default='fine', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='ethical_concerns',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='inappropriate_self_citations',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='logical_coherence',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='originality',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_merit',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_recommendation',
            field=models.CharField(choices=[('accept', 'Accept in present form'), ('minor_revision', 'Accept after minor revision'), ('major_revision', 'Reconsider after major revision'), ('reject', 'Reject')], default='major_revision', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='plagiarism_detected',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='references_adequate',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='references_relevant',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='research_design',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='results_presented',
            field=models.CharField(choices=[('yes', 'Yes'), ('can_be_improved', 'Can be improved'), ('must_be_improved', 'Must be improved'), ('not_applicable', 'Not applicable')], default='can_be_improved', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='structure_clarity',
            field=models.CharField(choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low'), ('no_answer', 'No answer')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='wants_final_notification',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conferences.submission'),
        ),
    ]
