# Generated by Django 6.0.4 on 2026-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0018_remove_review_comment_remove_review_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='auto_score',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
