# Generated by Django 6.0.4 on 2026-05-14 06:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0033_review_round_rereview_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_publication_file',
            field=models.FileField(blank=True, help_text='Final print-ready paper uploaded by the layout reviewer.', null=True, upload_to='final_publication_papers/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('paper_submitted', 'Paper submission confirmation'), ('reviewer_assigned', 'Reviewer assigned'), ('revision_requested', 'Content revision requested'), ('revision_uploaded', 'Content revision uploaded'), ('accepted_for_layout', 'Accepted for layout review'), ('layout_revision_requested', 'Layout corrections requested'), ('layout_revision_uploaded', 'Layout corrected paper uploaded'), ('final_accepted', 'Accepted for publication'), ('rejected', 'Rejected')], max_length=80),
        ),
    ]
