# Generated by Django 6.0.4 on 2026-05-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0034_submission_final_publication_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='footer_address',
            field=models.CharField(blank=True, help_text='Address shown in the footer.', max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='footer_contact_email',
            field=models.EmailField(blank=True, help_text='Contact email shown in the footer.', max_length=254),
        ),
        migrations.AddField(
            model_name='conference',
            name='footer_copyright',
            field=models.CharField(blank=True, help_text='Copyright text shown at the bottom of the footer.', max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='footer_description',
            field=models.TextField(blank=True, help_text='Short text shown in the conference footer.'),
        ),
        migrations.AddField(
            model_name='conference',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Optional logo shown in the footer.', null=True, upload_to='conference_footer/'),
        ),
        migrations.CreateModel(
            name='ConferenceFooterPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conference_footer_partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_partners', to='conferences.conference')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
