# Generated by Django 6.0.4 on 2026-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0035_conference_footer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencefooterpartner',
            name='partner_type',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('coorganizer', 'Co-organizer')], default='organizer', max_length=20),
        ),
        migrations.AlterField(
            model_name='conference',
            name='footer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='conference',
            name='footer_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='conference',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='conference',
            name='footer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='conference_footer/'),
        ),
    ]
