# Generated by Django 6.0.4 on 2026-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0047_force_overview_layout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title_sr',
            field=models.TextField(),
        ),
    ]
