# Generated by Django 6.0.4 on 2026-05-17 18:36

import conferences.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0048_alter_conference_title_en_alter_conference_title_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceinfocard',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='conference_files/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='commented_paper_file',
            field=models.FileField(blank=True, help_text='Optional reviewer-uploaded paper with comments for the author.', max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='reviewer_commented_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='abstracts/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='anonymized_paper_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='anonymous_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_publication_file',
            field=models.FileField(blank=True, help_text='Final print-ready paper uploaded by the layout reviewer.', max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='final_publication_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='full_paper_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='layout_revised_paper_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='layout_revised_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revised_paper_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='revised_papers/'),
        ),
    ]
