# Generated by Django 6.0.4 on 2026-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_alter_conferenceinfocard_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='coauthors_data',
            field=models.JSONField(blank=True, default=list, help_text='Structured co-author data.'),
        ),
    ]
