# Generated by Django 6.0.4 on 2026-05-17 22:26

import conferences.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0050_submission_coauthors_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='coauthors_data',
        ),
        migrations.AddField(
            model_name='submission',
            name='original_submission_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=conferences.storage_backends.HybridDocumentStorage(), upload_to='original_submission_papers/'),
        ),
    ]
