# Generated by Django 6.0.4 on 2026-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0054_submission_author_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under content review'), ('reviews_completed', 'Content review completed'), ('revision_required', 'Revision requested'), ('revised_submitted', 'Revised paper submitted'), ('accepted_for_layout', 'Accepted for layout review'), ('layout_revision_required', 'Layout corrections requested'), ('layout_revision_submitted', 'Layout corrected paper submitted'), ('final_accepted', 'Final accepted'), ('accepted', 'Accepted (legacy)'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
    ]
