# Generated by Django 6.0.4 on 2026-05-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0055_alter_submission_status'),
        ('conferences', '0056_overview_hero_layout_fields'),
    ]

    operations = [
    ]
