# Generated by Django 6.0.4 on 2026-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0057_merge_20260519_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='coauthor_titles',
        ),
        migrations.AlterField(
            model_name='submission',
            name='first_author_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
