# Generated by Django 6.0.4 on 2026-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0058_remove_submission_coauthor_titles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='coauthor_titles',
            field=models.TextField(blank=True, help_text='Enter co-author titles, one per line.'),
        ),
    ]
