# Generated by Django 6.0.4 on 2026-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0060_conference_overview_colours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('committee_login_info', '1. Scientific Committee login information'), ('reviewer_topics_request', 'Reviewer topic selection request'), ('paper_submitted', '2. Submission confirmation – author'), ('coauthor_submission_confirmation', '3. Submission confirmation – co-author'), ('review_invitation', '4. Invitation to review manuscript'), ('review_declined_judge', '4a. Reviewer declined invitation – Judge notification'), ('review_declined_author', '4b. Reviewer declined invitation – Author notification'), ('review_request_accepted', '5. Review request accepted'), ('review_initiated', '6. Review initiated – author notification'), ('review_due_soon', '7. Reminder: review due soon'), ('review_overdue', '8. Reminder: review overdue'), ('review_received', '9. Confirmation of review receipt'), ('rereview_invitation', '10. Invitation to re-evaluate revised manuscript'), ('reviewer_editor_decision', '11. Reviewer notification of editor decision'), ('review_completed_author', '12. Review completed – author decision'), ('manuscript_accepted', '13. Manuscript accepted for publication'), ('layout_correction_needed', '14. Layout correction needed'), ('layout_correction_submitted', '15. Author correction submitted'), ('reviewer_assigned', 'Legacy: reviewer assigned'), ('revision_requested', 'Legacy: content revision requested'), ('revision_uploaded', 'Legacy: content revision uploaded'), ('accepted_for_layout', 'Legacy: accepted for layout review'), ('layout_revision_requested', 'Legacy: layout corrections requested'), ('layout_revision_uploaded', 'Legacy: layout corrected paper uploaded'), ('final_accepted', 'Legacy: final accepted'), ('rejected', 'Legacy: rejected')], max_length=80),
        ),
    ]
