# Generated by Django 6.0.4 on 2026-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0063_overview_extra_background_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='overview_hero_image_width',
            field=models.PositiveIntegerField(default=78),
        ),
    ]
