# Generated by Django 6.0.4 on 2026-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0064_conference_overview_hero_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='overview_info_area_background_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='overview_partners_area_background_color',
            field=models.CharField(default='#eef2f1', max_length=20),
        ),
    ]
