# Generated by Django 6.0.4 on 2026-05-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0065_conference_overview_info_area_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='overview_info_area_background_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='overview_partners_area_background_color',
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_background_color',
            field=models.CharField(default='#f4f1e6', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_background_image_opacity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_background_image_width',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_card_background',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_card_padding',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_card_radius',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_container_width',
            field=models.PositiveIntegerField(default=880),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_header_background',
            field=models.CharField(default='#13365c', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_left_margin',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_logo_width',
            field=models.PositiveIntegerField(default=140),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_text_color',
            field=models.CharField(default='#374151', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='hub_title_color',
            field=models.CharField(default='#0f3d2e', max_length=20),
        ),
    ]
