# Generated by Django 6.0.4 on 2026-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0066_remove_conference_overview_info_area_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='hub_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='conference_hub/'),
        ),
    ]
