# Generated by Django 6.0.4 on 2026-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0067_conference_hub_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image_opacity',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_background',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_padding',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_radius',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_container_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_header_background',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_left_margin',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_logo_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_text_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_title_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='overview_hero_image_width',
        ),
        migrations.AddField(
            model_name='submission',
            name='author_revision_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under content review'), ('reviews_completed', 'Content review completed'), ('reviewed_by_reviewer', 'Reviewed by reviewer'), ('revision_required', 'Revision requested'), ('revised_submitted', 'Revised paper submitted'), ('accepted_for_layout', 'Accepted for layout review'), ('layout_revision_required', 'Layout corrections requested'), ('layout_revision_submitted', 'Layout corrected paper submitted'), ('final_accepted', 'Final accepted'), ('accepted', 'Accepted (legacy)'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
    ]
