# Generated by Django 6.0.4 on 2026-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0078_submission_status_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image_opacity',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_background_image_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_background',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_padding',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_card_radius',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_container_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_header_background',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_left_margin',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_logo_width',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_text_color',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='hub_title_color',
        ),
        migrations.AddField(
            model_name='submission',
            name='author_publication_approved_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the author approved final files for publication.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='author_publication_comment',
            field=models.TextField(blank=True, help_text='Author comments on final publication proof files.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='author_publication_decision_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when authors approved or requested corrections to publication proof files.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_publication_pdf_file',
            field=models.FileField(blank=True, help_text='Final PDF file prepared by the layout editor for author proof approval.', max_length=500, null=True, upload_to='final_publication_pdf/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_publication_word_file',
            field=models.FileField(blank=True, help_text='Final Word file prepared by the layout editor for author proof approval.', max_length=500, null=True, upload_to='final_publication_word/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('committee_login_info', '1. Scientific Committee login information'), ('reviewer_topics_request', 'Reviewer topic selection request'), ('paper_submitted', '2. Submission confirmation – author'), ('coauthor_submission_confirmation', '3. Submission confirmation – co-author'), ('review_invitation', '4. Invitation to review manuscript'), ('review_invitation_cancelled', '4a. Review invitation cancelled – Reviewer notification'), ('review_declined_judge', '4b. Reviewer declined invitation – Judge notification'), ('review_declined_author', '4c. Reviewer declined invitation – Author notification'), ('review_request_accepted', '5. Review request accepted'), ('review_initiated', '6. Review initiated – author notification'), ('review_due_soon', '7. Reminder: review due soon'), ('review_overdue', '8. Reminder: review overdue'), ('review_received', '9. Confirmation of review receipt'), ('rereview_invitation', '10. Invitation to re-evaluate revised manuscript'), ('reviewer_editor_decision', '11. Reviewer notification of editor decision'), ('review_completed_author', '12. Review completed – author decision'), ('publication_proof_author_approval', '13a. Author approval required for final publication files'), ('publication_proof_corrections_requested', '13b. Authors requested corrections to final publication files'), ('manuscript_accepted', '13. Manuscript accepted for publication'), ('layout_correction_needed', '14. Layout correction needed'), ('layout_correction_submitted', '15. Author correction submitted'), ('reviewer_assigned', 'Legacy: reviewer assigned'), ('revision_requested', 'Legacy: content revision requested'), ('revision_uploaded', 'Legacy: content revision uploaded'), ('accepted_for_layout', '12a. Manuscript accepted for layout preparation'), ('layout_revision_requested', 'Legacy: layout corrections requested'), ('layout_revision_uploaded', 'Legacy: layout corrected paper uploaded'), ('final_accepted', 'Legacy: final accepted'), ('rejected', 'Legacy: rejected')], max_length=80),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_publication_file',
            field=models.FileField(blank=True, help_text='Legacy final print-ready paper uploaded by the layout reviewer.', max_length=500, null=True, upload_to='final_publication_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='revised_paper_file',
            field=models.FileField(blank=True, help_text='Revised version of the manuscript (clean file).', max_length=500, null=True, upload_to='revised_papers/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewer_acceptance_pending', 'Reviewer acceptance pending'), ('under_review', 'Under content review'), ('reviews_completed', 'Content review completed'), ('reviewed_by_reviewer', 'Reviewed by reviewer'), ('revision_required', 'Revision requested'), ('revised_submitted', 'Revised paper submitted'), ('paper_revision_completed', 'Paper revision completed'), ('accepted_for_layout', 'Accepted for layout review'), ('layout_revision_required', 'Layout corrections requested'), ('layout_revision_submitted', 'Layout corrected paper submitted'), ('awaiting_author_publication_approval', 'Awaiting author publication approval'), ('final_accepted', 'Final approved for publication'), ('accepted', 'Accepted (legacy)'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
